
-- Fix remaining 5 songs with corrupted characters
UPDATE songs SET title = 'CUANDO SAÚL SE LEVANTÓ CONTRA DAVID' WHERE title = 'CUANDO SAÚL SE LEVANT' || chr(65533) || ' CONTRA DAVID';
UPDATE songs SET title = 'DE BELÉN A JERUSALÉN' WHERE title LIKE 'DE BELÉN A JERUSAL%' AND title LIKE '%�%';
UPDATE songs SET title = 'DIOS HA PROMETIDO QUE ESTARÁ CONTIGO' WHERE title LIKE 'DIOS HA PROMETIDO QUE ESTAR%CONTIGO' AND title LIKE '%�%';
UPDATE songs SET title = 'MI ORGULLO ME SACÓ DEL JARDÍN' WHERE title LIKE 'MI ORGULLO ME SAC%DEL JARD%' AND title LIKE '%�%';
UPDATE songs SET title = 'TÚ VIENES CONTRA MÍ CON ESPADA Y JABALINA' WHERE title LIKE 'TÚ VIENES CONTRA M%CON ESPADA%' AND title LIKE '%�%';
